%YAML 1.1
---
groupId: com.xenoamess.docker
artifactId: dockerfile-maven-plugin
versioning:
  latest: 1.5.0-rc1
  release: 1.5.0-rc1
  versions:
  - 1.4.20
  - 1.4.21
  - 1.4.21-fx1
  - 1.4.22
  - 1.4.23
  - 1.4.24-beta1
  - 1.4.24
  - 1.4.25
  - 1.5.0-rc1
  lastUpdated: 20230207185502
