%YAML 1.1
---
groupId: com.xenoamess.docker
artifactId: dockerfile-maven-extension
versioning:
  latest: 1.4.22
  release: 1.4.22
  versions:
  - 1.4.20
  - 1.4.21
  - 1.4.21-fx1
  - 1.4.22
  lastUpdated: 20220119133747
