%YAML 1.1
---
groupId: com.xenoamess.docker
artifactId: dockerfile-maven-plugin
versioning:
  latest: 1.4.24
  release: 1.4.24
  versions:
  - 1.4.20
  - 1.4.21
  - 1.4.21-fx1
  - 1.4.22
  - 1.4.23
  - 1.4.24-beta1
  - 1.4.24
  lastUpdated: 20220125195003
