%YAML 1.1
---
groupId: com.spotify
artifactId: dockerfile-maven-extension
versioning:
  latest: 1.3.5
  release: 1.3.5
  versions:
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - 1.3.5
  lastUpdated: 20170816200450
