%YAML 1.1
---
groupId: com.spotify
artifactId: dockerfile-maven
versioning:
  latest: 1.3.1
  release: 1.3.1
  versions:
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.3.0
  - 1.3.1
  lastUpdated: 20170630134029
