%YAML 1.1
---
groupId: com.spotify
artifactId: dockerfile-maven-extension
versioning:
  latest: 1.4.5
  release: 1.4.5
  versions:
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - 1.3.5
  - 1.3.6
  - 1.3.7
  - 1.4.0
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  lastUpdated: 20181001155627
