%YAML 1.1
---
groupId: com.salesforce.dockerfile-image-update
artifactId: dockerfile-image-update
versioning:
  latest: 1.0.9
  release: 1.0.9
  versions:
  - 1.0.2
  - 1.0.3
  - 1.0.4
  - 1.0.5
  - 1.0.6
  - 1.0.7
  - 1.0.8
  - 1.0.9
  lastUpdated: 20180720181659
