%YAML 1.1
---
groupId: com.salesforce.dockerfile-image-update
artifactId: dockerfile-image-update-itest
versioning:
  latest: 1.0.3
  release: 1.0.3
  versions:
  - 1.0.2
  - 1.0.3
  lastUpdated: 20180129211207
