%YAML 1.1
---
groupId: org.wso2.carbon.identity.framework
artifactId: compatibility-settings-mgt-feature
versioning:
  latest: 7.8.681
  release: 7.8.681
  versions:
  - 7.8.677
  - 7.8.678
  - 7.8.679
  - 7.8.680
  - 7.8.681
  lastUpdated: 20260210180921
