%YAML 1.1
---
groupId: org.wso2.carbon.identity.framework
artifactId: compatibility-settings-mgt
versioning:
  latest: 7.10.0
  release: 7.10.0
  versions:
  - 7.8.677
  - 7.8.678
  - 7.8.679
  - 7.8.680
  - 7.8.681
  - 7.8.682
  - 7.8.683
  - 7.8.684
  - 7.8.685
  - 7.10.0
  lastUpdated: 20260212145544
