%YAML 1.1
---
groupId: org.wso2.carbon.identity.framework
artifactId: compatibility-settings-mgt
versioning:
  latest: 7.8.677
  release: 7.8.677
  versions:
  - 7.8.677
  lastUpdated: 20260207095936
