%YAML 1.1
---
groupId: org.wso2.carbon.identity.framework
artifactId: org.wso2.carbon.identity.compatibility.settings.management.server.feature
versioning:
  latest: 7.8.684
  release: 7.8.684
  versions:
  - 7.8.677
  - 7.8.678
  - 7.8.679
  - 7.8.680
  - 7.8.681
  - 7.8.682
  - 7.8.683
  - 7.8.684
  lastUpdated: 20260211182106
