%YAML 1.1
---
groupId: ca.vanzyl
artifactId: dockerfile-maven-extension
versioning:
  latest: 1.4.17
  release: 1.4.17
  versions:
  - 1.4.14
  - 1.4.15
  - 1.4.16
  - 1.4.17
  lastUpdated: 20200414153824
