%YAML 1.1
---
modelVersion: 1.1.0
groupId: ca.vanzyl
artifactId: dockerfile-maven-plugin
versioning:
  latest: 1.4.19
  release: 1.4.19
  versions:
  - 1.4.15
  - 1.4.16
  - 1.4.17
  - 1.4.18
  - 1.4.19
  - 1.4.14
  lastUpdated: 20210104144601
