%YAML 1.1
---
groupId: ca.vanzyl
artifactId: dockerfile-maven
versioning:
  latest: 1.4.19
  release: 1.4.19
  versions:
  - 1.4.14
  - 1.4.15
  - 1.4.16
  - 1.4.17
  - 1.4.18
  - 1.4.19
  lastUpdated: 20200416174226
