%YAML 1.1
---
groupId: ca.vanzyl
artifactId: dockerfile-maven-plugin
versioning:
  latest: 1.4.18
  release: 1.4.18
  versions:
  - 1.4.14
  - 1.4.15
  - 1.4.16
  - 1.4.17
  - 1.4.18
  lastUpdated: 20200415220355
