%YAML 1.1
---
groupId: org.apache.kie.sonataflow
artifactId: sonataflow-addons-quarkus-asyncapi-deployment
versioning:
  latest: 10.2.0
  release: 10.2.0
  versions:
  - 10.2.0
  lastUpdated: 20260426205504
