%YAML 1.1
---
groupId: org.wso2.identity.webhook.event.handlers
artifactId: identity-webhook-event-handlers-feature
versioning:
  latest: 1.2.1
  release: 1.2.1
  versions:
  - 1.2.0
  - 1.2.1
  lastUpdated: 20260224085552
