%YAML 1.1
---
groupId: org.wso2.identity.webhook.event.handlers
artifactId: identity-webhook-event-handlers
versioning:
  latest: 1.2.4
  release: 1.2.4
  versions:
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.2.4
  lastUpdated: 20260526090304
