%YAML 1.1
---
groupId: org.wso2.identity.webhook.event.handlers
artifactId: org.wso2.identity.webhook.event.handlers.server.feature
versioning:
  latest: 1.2.0
  release: 1.2.0
  versions:
  - 1.2.0
  lastUpdated: 20260211115840
