%YAML 1.1
---
groupId: org.wso2.identity.webhook.event.handlers
artifactId: org.wso2.identity.webhook.wso2.event.handler
versioning:
  latest: 1.2.3
  release: 1.2.3
  versions:
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.2.3
  lastUpdated: 20260331085525
