%YAML 1.1
---
groupId: io.quarkiverse.helm
artifactId: quarkus-helm-spi
versioning:
  latest: 1.2.7
  release: 1.2.7
  versions:
  - 1.2.4
  - 1.2.5
  - 1.2.6
  - 1.2.7
  - 1.3.0
  - 1.4.0
  lastUpdated: 20250123064921
