%YAML 1.1
---
groupId: org.wso2.carbon.identity.integration.ui.templates
artifactId: org.wso2.carbon.identity.integration.ui.templates.applications.nuxt-application
versioning:
  latest: 1.1.1
  release: 1.1.1
  versions:
  - 1.1.1
  lastUpdated: 20260526041418
