%YAML 1.1
---
groupId: org.wso2.carbon.identity.integration.ui.templates
artifactId: org.wso2.carbon.identity.integration.ui.templates.applications.agent-application
versioning:
  latest: 1.1.3
  release: 1.1.3
  versions:
  - 1.1.3
  lastUpdated: 20260602045726
