%YAML 1.1
---
groupId: org.wso2.carbon.commons
artifactId: org.wso2.carbon.logging.remote.config.mgt.ui.feature
versioning:
  latest: 4.14.0
  release: 4.14.0
  versions:
  - 4.9.6
  - 4.9.7
  - 4.9.10
  - 4.9.19
  - 4.9.21
  - 4.10.8
  - 4.11.2
  - 4.12.0
  - 4.14.0
  lastUpdated: 20260217052103
