%YAML 1.1
---
groupId: org.wso2.carbon.identity.auth.organization.login
artifactId: org.wso2.carbon.identity.application.authenticator.handler.organization.identifier
versioning:
  latest: 1.2.2
  release: 1.2.2
  versions:
  - 1.2.2
  lastUpdated: 20260302182125
